esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: "wt32-sc01.esphome"
    version: "1.0"

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

psram:
  mode: quad
  speed: 80MHz

# SPI for display
spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

# I2C for touchscreen
i2c:
  sda: GPIO18
  scl: GPIO19
  scan: true

# Backlight control
output:
  - platform: ledc
    pin: GPIO23
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Backlight"
    id: backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 0s

# Display - ST7796 480x320 (landscape mode)
display:
  - platform: ili9xxx
    model: ST7796
    cs_pin: GPIO15
    dc_pin: GPIO21
    reset_pin: GPIO22
    id: my_display
    auto_clear_enabled: false
    update_interval: never
    invert_colors: false
    data_rate: 40MHz
    transform:
      swap_xy: true
    dimensions:
      width: 480
      height: 320
      offset_width: 0
      offset_height: 0

# Touchscreen - FT6336U
touchscreen:
  - platform: ft63x6
    id: my_touchscreen
    address: 0x38
    interrupt_pin: GPIO39
    display: my_display
    transform:
      swap_xy: true
      mirror_y: true
    on_touch:
      - light.turn_on:
          id: backlight
          brightness: 100%
